class AgoraConfig {
  // Agora App ID
  static const String appId = "1ae25a0eafe74bb59dbd4510981079c3";

  // Default channel name (can be customized per call)
  // static const String defaultChannelName = "consultnow";

  // Token (MUST be generated by YOUR API server in production)
  //
  // HOW IT WORKS:
  // 1. Your backend API generates both channel_name AND agora_token
  // 2. Backend uses Agora SDK (Node.js, PHP, Python, etc.) to create token
  // 3. Token is tied to: AppID, AppCertificate, channelName, userId, and expiration
  // 4. Your API returns: { chanel_id: "consultnow_4", agora_token: "006..." }
  // 5. Flutter app uses both to join the call
  //
  // For TESTING ONLY, you can use null (if Agora project allows tokenless access)
  // For PRODUCTION, token MUST come from your backend API
  //
  // Current mode: Testing (tokenless) - Replace with token from API:
  // static const String? token = ""; // Try empty string instead of null
  // Example: static const String? token = "your_generated_token_here";

  // TEMPORARY FIX: Uncomment the line below and add your token
  // static const String? token = "YOUR_TOKEN_HERE";

  // ALTERNATIVE: Try with empty string instead of null
  // static const String? token = "";

  // Enable tokenless access for testing (set to false for production)
  // static const bool enableTokenlessAccess = true;

  // User ID (can be generated or use existing user ID)
  static int generateUserId() {
    return DateTime.now().millisecondsSinceEpoch % 100000;
  }

  // Generate channel name for specific appointment
  static String generateChannelName(int appointmentId) {
    return "consultnow_$appointmentId";
  }
}
